### ISSUE TITLE
 Dimension out of range (expected to be in range of [-1, 0], but got 1) 

### ISSUE THREAD

**Issue by ngocson1804** [TAMU-VITA/ABD-Net#12]
Hi,
When i run source code to evaluate model. I changed backbond to inceptionv4. But i got an error 
" Dimension out of range (expected to be in range of [-1, 0], but got 1) ". Can you explain why?
thank you

**Comment by hsfzxjy** [comment]
Currently we have no support for backbones other than ResNet-50. The other backbones exist because our codebase is adapted from another repo, and we didn't delete irrelevant files completely. But you can try apply our model on other backbones like inceptionv4, if you want. I think it's not so difficult to write the code.
Thanks!
